apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-backend
  name: go-backend-svc
  namespace: go-app
spec:
  ports:
  - name: http         # Add a port name here
    port: 9191
    protocol: TCP
    targetPort: 9191
  selector:
    app: go-backend