apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-frontend
  name: go-frontend-svc
  namespace: go-app
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: go-frontend
status:
  loadBalancer: {}