apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ingress
  namespace: go-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "internal-ca-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - go-app.local
      secretName: internal-ca-cert-go-app-local
  rules:
    - host: go-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-frontend-svc
                port:
                  number: 9090
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: go-backend-svc
                port:
                  number: 9191