apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: go-postgres
  namespace: go-app
spec:
  instances: 2

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: app
      owner: go_app_user
      secret:
        name: go-postgres-credentials